version: 2
updates:
  # Enable version updates for Rust
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "toddbush"
    assignees:
      - "toddbush"
    commit-message:
      prefix: "chore"
    labels:
      - "dependencies"
      - "rust"
    ignore:
      # Ignore major version updates for these packages
      - dependency-name: "git2"
        update-types: ["version-update:semver-major"]
      - dependency-name: "chrono"
        update-types: ["version-update:semver-major"]
      # Ignore development dependencies that might cause issues
      - dependency-name: "cargo-tarpaulin"
        update-types: ["version-update:semver-major"] 