[package]
name = "grit"
version = "0.2.0"
authors = ["Todd Bush"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
docopt = "1.0"
serde = "1.0.104"
serde_derive = "1.0.104"
git2 = "0.11"
log = "0.4.8"
simple_logger = "^1.3.0"
prettytable-rs = "^0.8"
indicatif = "0.13.0"
chrono = "0.4.11"
csv="1.1.3"
plotters = { version = "^0.2.12", default_features=false, features=["image_encoder", "datetime", "line_series", "point_series"] }
glob="0.3.0"
tokio = { version = "0.2.20", features = ["macros", "rt-core", "rt-threaded"] }
futures = "0.3.4"
charts = "0.3.0"

[dev-dependencies]
tempfile = "3.1.0"
