[package]
name = "grit"
version = "0.3.1"
authors = ["Todd Bush"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
docopt = "^1.1"
clap = "3.0.0-beta.2"
serde = "1.0.104"
serde_derive = "1.0.104"
git2 = "^0.13"
log = "^0.4"
simple_logger = "^1.11"
prettytable-rs = "^0.8"
indicatif = "^0.15"
chrono = "^0.4"
csv="^1.1"
glob="^0.3"
tokio = { version = "^0.2", features = ["macros", "rt-core", "rt-threaded"] }
futures = "^0.3"
charts = "^0.3"
anyhow = "^1.0"

[dev-dependencies]
tempfile = "3.1.0"
