name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: rustlang/rust:nightly
    env:
      working-directory: ${{ github.workspace }}

    steps:
    - uses: 98w/action-debugger@v0.1
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
      working-directory: ${{ env.working-directory }}

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    container: rustlang/rust:nightly
    env:
      RUST_BACKTRACE: full

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - uses: 98w/action-debugger@v0.1

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -- --test-threads=1 --nocapture
